In [6]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 100.00%


In [5]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
cm=confusion_matrix(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(cm)

Accuracy: 100.00%
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")
print("\nEnter the flower measurements:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))
newrow = np.array([[sepal_length,sepal_width,petal_length,petal_width]])
prediction = nb_classifier.predict(newrow)
species = data.target_names[prediction[0]]
print(f"\nPredicted Iris species: {species}")


Accuracy of Naive Bayes: 1.00

Enter the flower measurements:


Sepal length (cm):  5
Sepal width (cm):  7
Petal length (cm):  3
Petal width (cm):  5



Predicted Iris species: virginica


In [4]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
df = pd.read_csv("fruit.csv")
print(df.head())
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred = nb_classifier.predict(X_test)
accuracy =accuracy_score(y_test, y_pred)
print(f"Accuracy of Naive Bayes: {accuracy:.2f}")


weight=float(input("enter weight:"))
size=float(input("enter size:"))
price=float(input("enter price:"))


fruits=[[weight,size,price]]

print("predicted fruit",prediction[0])

   Weight  Size  Price  Label
0     150     7     80  Apple
1     160     7     85  Apple
2     170     8     90  Apple
3     180     8     95  Apple
4     190     9    100  Apple
Accuracy of Naive Bayes: 0.80


enter weight: 160
enter size: 7
enter price: 120


predicted fruit 2


In [9]:
%pip install scikit-learn numpy


Note: you may need to restart the kernel to use updated packages.
