In [3]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

#addition
C=A+B

#substraction
C=A-B

E=A*B

F=np.dot(A,B)

A_transpose=A.T

print("addition")
print(C)
print("\nSubstraction")
print(C)
print("\nElement-wise Multiplication:")
print(E)
print("\nMatrix Multiplication")
print(F)
print("\nTranspose")
print(A_transpose)

addition
[[-4 -4]
 [-4 -4]]

Substraction
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication
[[19 22]
 [43 50]]

Transpose
[[1 3]
 [2 4]]


In [5]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])

U,S,VT=np.linalg.svd(X)

n_components=2

X_reconstructed = np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),
                                                          
VT[:n_components,:]))
print("original matrix:")
print(X)
print("\nREconstructed Matrix (with reduced dimensions):")
print(X_reconstructed)


original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

REconstructed Matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
